BEGIN TRY

BEGIN TRANSACTION;

Use DbUser;

DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS ImagesType;
DROP TABLE IF EXISTS Images;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS ProfessionalInformations;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
	Id INT IDENTITY(1,1),
	Name VARCHAR(200) NOT NULL,
	Email VARCHAR(200) DEFAULT NULL,
	DDD CHAR(2) DEFAULT NULL,
	Phone CHAR(9) DEFAULT NULL,
	Password VARCHAR(50) DEFAULT NULL
);

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY (Id);

CREATE TABLE Address(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	AddressLine VARCHAR(100) DEFAULT NULL,
	Number INT DEFAULT NULL,
	Complement VARCHAR(100) DEFAULT NULL,
	City VARCHAR(100) DEFAULT NULL,
	State VARCHAR(100) DEFAULT NULL,
	Country VARCHAR(100) DEFAULT NULL,
	ZipCode VARCHAR(100) DEFAULT NULL,
	Latitude DECIMAL(9,6) DEFAULT NULL,
	Longitude DECIMAL(9,6) DEFAULT NULL
);

ALTER TABLE Address
ADD CONSTRAINT PK_Address PRIMARY KEY (Id);

ALTER TABLE Address
ADD CONSTRAINT FK_Address_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);

CREATE TABLE ImagesType(
	Id INT IDENTITY(1,1),
	Name VARCHAR(50)
);

ALTER TABLE ImagesType
ADD CONSTRAINT PK_ImagesType PRIMARY KEY (Id);

CREATE TABLE Images(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	ImagesTypeId INT NOT NULL,
	Value VARCHAR(500) NOT NULL,
);

ALTER TABLE Images
ADD CONSTRAINT PK_Images PRIMARY KEY (Id);

ALTER TABLE Images
ADD CONSTRAINT FK_Images_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);

ALTER TABLE Images
ADD CONSTRAINT FK_Images_ImagesTypeId
FOREIGN KEY (ImagesTypeId) REFERENCES ImagesType(Id);

CREATE TABLE ProfessionalInformations(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	Description VARCHAR(MAX)
);

ALTER TABLE ProfessionalInformations
ADD CONSTRAINT PK_ProfessionalInformations PRIMARY KEY (Id);

ALTER TABLE ProfessionalInformations
ADD CONSTRAINT FK_ProfessionalInformations_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);


CREATE TABLE Services(
	Id INT IDENTITY(1,1),
	ProfessionalInformationsId INT NOT NULL,
	Name VARCHAR(50) NOT NULL
);

ALTER TABLE Services
ADD CONSTRAINT PK_Services PRIMARY KEY (Id);

ALTER TABLE Services
ADD CONSTRAINT FK_Services_ProfessionalInformationsId
FOREIGN KEY (ProfessionalInformationsId) REFERENCES ProfessionalInformations(Id);


COMMIT TRANSACTION;

END TRY

BEGIN CATCH

	ROLLBACK TRANSACTION;

END CATCH
