BEGIN TRY

BEGIN TRANSACTION;

DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Images;
DROP TABLE IF EXISTS ImageType;
DROP TABLE IF EXISTS Services;
DROP TABLE IF EXISTS ProfessionalInformations;
DROP TABLE IF EXISTS Ratings;
DROP TABLE IF EXISTS RatingType;
DROP TABLE IF EXISTS Phones;
DROP TABLE IF EXISTS Users;


CREATE TABLE Users(
	Id INT IDENTITY(1,1),
	Name VARCHAR(200) NOT NULL,
	Email VARCHAR(200) DEFAULT NULL,
	Password VARCHAR(50) DEFAULT NULL
);

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY (Id);

CREATE TABLE Address(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	AddressLine VARCHAR(100) DEFAULT NULL,
	Number INT DEFAULT NULL,
	Complement VARCHAR(100) DEFAULT NULL,
	City VARCHAR(100) DEFAULT NULL,
	State VARCHAR(100) DEFAULT NULL,
	Country VARCHAR(100) DEFAULT NULL,
	ZipCode VARCHAR(100) DEFAULT NULL,
	Latitude DECIMAL(9,6) DEFAULT NULL,
	Longitude DECIMAL(9,6) DEFAULT NULL
);

ALTER TABLE Address
ADD CONSTRAINT PK_Address PRIMARY KEY (Id);

ALTER TABLE Address
ADD CONSTRAINT FK_Address_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);

CREATE TABLE ImageType(
	Id INT IDENTITY(1,1),
	Name VARCHAR(50)
);

ALTER TABLE ImageType
ADD CONSTRAINT PK_ImagesType PRIMARY KEY (Id);

CREATE TABLE Images(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	ImageTypeId INT NOT NULL,
	Value VARCHAR(500) NOT NULL,
);

ALTER TABLE Images
ADD CONSTRAINT PK_Images PRIMARY KEY (Id);

ALTER TABLE Images
ADD CONSTRAINT FK_Images_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);

ALTER TABLE Images
ADD CONSTRAINT FK_Images_ImageTypeId
FOREIGN KEY (ImageTypeId) REFERENCES ImageType(Id);

CREATE TABLE ProfessionalInformations(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	Description VARCHAR(MAX)
);

ALTER TABLE ProfessionalInformations
ADD CONSTRAINT PK_ProfessionalInformations PRIMARY KEY (Id);

ALTER TABLE ProfessionalInformations
ADD CONSTRAINT FK_ProfessionalInformations_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);


CREATE TABLE Services(
	Id INT IDENTITY(1,1),
	ProfessionalInformationsId INT NOT NULL,
	Name VARCHAR(50) NOT NULL
);

ALTER TABLE Services
ADD CONSTRAINT PK_Services PRIMARY KEY (Id);

ALTER TABLE Services
ADD CONSTRAINT FK_Services_ProfessionalInformationsId
FOREIGN KEY (ProfessionalInformationsId) REFERENCES ProfessionalInformations(Id);



CREATE TABLE RatingType(
	Id INT IDENTITY(1,1),
	Description VARCHAR(50) NOT NULL
);

ALTER TABLE RatingType
ADD CONSTRAINT PK_RatingType PRIMARY KEY (Id);

CREATE TABLE Ratings(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	RatingTypeId INT NOT NULL,
	RatingValue DECIMAL(10,2)
);

ALTER TABLE Ratings
ADD CONSTRAINT PK_Ratings PRIMARY KEY (Id);

ALTER TABLE Ratings
ADD CONSTRAINT FK_Ratings_RatingTypeId
FOREIGN KEY (RatingTypeId) REFERENCES RatingType(Id);

ALTER TABLE Ratings
ADD CONSTRAINT FK_Ratings_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);

CREATE TABLE Phones(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	DDD CHAR(2) DEFAULT NULL,
	PhoneNumber CHAR(9) DEFAULT NULL
);

ALTER TABLE Phones
ADD CONSTRAINT PK_Phone PRIMARY KEY (Id);


COMMIT TRANSACTION;

END TRY

BEGIN CATCH

	Print(CONCAT('Ocorreu um erro: ', @@ERROR));
	ROLLBACK TRANSACTION;

END CATCH
