CREATE TABLE RatingType(
	Id INT IDENTITY(1,1),
	Description VARCHAR(50) NOT NULL
);

ALTER TABLE RatingType
ADD CONSTRAINT PK_RatingType PRIMARY KEY (Id);

CREATE TABLE Rating(
	Id INT IDENTITY(1,1),
	UserId INT NOT NULL,
	RatingTypeId INT NOT NULL,
	RatingValue DECIMAL(10,2)
);

ALTER TABLE Rating
ADD CONSTRAINT PK_Rating PRIMARY KEY (Id);

ALTER TABLE Rating
ADD CONSTRAINT FK_Rating_RatingTypeId
FOREIGN KEY (RatingTypeId) REFERENCES RatingType(Id);

ALTER TABLE Rating
ADD CONSTRAINT FK_Rating_UserId
FOREIGN KEY (UserId) REFERENCES Users(Id);


